### ISSUE TITLE
http://jfaden.net/HapiServerDemo/hapi/info?id=a_test_of_an_invalid_id_by_verifier-nodejs fails with note to report here

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#1]
I was told to report this here:

http://jfaden.net/HapiServerDemo/hapi/info?id=a_test_of_an_invalid_id_by_verifier-nodejs
  Pass: is.ContentType() Expect HTTP Content-Type to match /^application\/json/; Got: application/json;charset=UTF-8
  Warn: is.CORSAvailable() To enable AJAX clients, want CORS HTTP Headers Access-Control-Allow-{Origin,Methods,Headers} = {*, GET, Content-Type}; Got: Access-Control-Allow-{Origin,Methods,Headers} = {undefined, undefined, undefined}
  Pass: Expect HTTP code to be 404; Got: 404
  Warn: Want HTTP message to match 'HAPI' and '1406'' for clients who do not have access to response body for HTTP 400-level errors; Got: Not Found
  Pass: is.JSONparsable() Expect JSON.parse(response) to not throw error; Got: no error
  Pass: is.HAPIJSON() Expect body to be valid error14xx schema; Got: is valid
  Pass: Expect HAPI code to be 1406; Got: 1406
Problem with verification server (Uncaught Exception). Aborting. Please report last URL shown in report to https://github.com/hapi-server/verifier-nodejs/issues

**Comment by rweigel** [comment]
1e62fb73b03082184ce5209f8e940cd8f6325157
