### ISSUE TITLE
Invalid URL to HAPI server produces access errors.

### ISSUE THREAD

**Issue by toddking** [hapi-server/verifier-nodejs#16]
I wanted to check a specific dataset with the verifier and entered the URL:

http://tsds.org/verify-hapi?url=https://pds-ppi.igpp.ucla.edu/hapi?id=urn:nasa:pds:maven.anc:data.drf.eps

Thinking the URL should be similar to calling the HAPI directly. The error is using "?" in the URL rather than "&" to make the "id=" a separate parameter.

The messages returned from the verifier indicate a basic error with contacting the HAPI server.

It would be nice if it indicated an invalid URL since it contains parameters.

**Comment by rweigel** [comment]
Thanks for pointing this out. I'll make an update so that a proper error is returned. I need to think about implications of allowing an unencoded reserved character in the parameter value for id, but my preference would be to silently allow it.

**Comment by rweigel** [comment]
I now realize that a more complete solution would require me to take urls like

`verify-hapi?url=http//server/hapi/info?id=abc`

and

`verify-hapi?url=http//server/hapi/data?id=abc&parameters=...&time.min=...&time.max=...`

And internally re-write them by stripping out the "/data" and "/info" as 

`verify-hapi?url=http//server/hapi&id=abc`

and

`verify-hapi?url=http//server/hapi?id=abc&parameters=...&time.min=...&time.max=...`

I'll add that in a future commit.

**Comment by rweigel** [comment]
Note that in the most recent commit, I now accept "parameters" as an argument (as well as "parameter" as before) to make the API consistent even though the verifier only checks the first parameter if given. In a future commit, I'll make the verifier check parameter combinations if given.

**Comment by rweigel** [comment]
Fixed some time in the past.
