### ISSUE TITLE
"label" is marked as incorrect

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#20]
I get the error:

~~~~~
http://jfaden.net/HapiServerDemo/hapi/info?id=0B000800408DD710
  Pass: is.HTTP200() Expect HTTP status code to be 200; Got: HTTP status 200
  Pass: is.ContentType() Expect HTTP Content-Type to match /^application\/json/; Got: application/json;charset=UTF-8
  Pass: is.JSONparsable() Expect JSON.parse(response) to not throw error; Got: no error
  Fail: is.HAPIJSON() Expect body to be valid info schema; Got: 
 [
     "parameters[1] additionalProperty 'label' exists in instance when not allowed"
 ]
  Pass: is.Unique() Expect all 'name' values in objects in parameters array to be unique; Got: All unique.
  Pass: is.TimeFirstParameter() First parameter should (not must) be named 'Time' b/c clients will likely label first parameter as 'Time' on plot to protect against first parameter names that are not sensible.; Got: Time
~~~~~

when I believe label is okay:
https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#info, search for "label"

**Comment by rweigel** [comment]
The error is correct. label is in the dev version of the spec, but not the 2.0 version:

https://github.com/hapi-server/data-specification/blob/master/hapi-2.0.0/HAPI-data-access-spec-2.0.0.md

There is no JSON schema for the dev version of the spec. I suppose I could allow a user to select the version of the spec to use and create a 2.1-dev version of the JSON schema, but I think we should really create a new release of the spec.

**Comment by jbfaden** [comment]
Ah, I wondered about that.  It would be nice to be able to set the version.  Also I see the message at the top now where it says the schema you are testing against.

**Comment by jbfaden** [comment]
We should also have a "dev" one which can change, and presumably would be copied over to a versioned one once things are set.
