### ISSUE TITLE
Timed out requests for metadata should try again

### ISSUE THREAD

**Issue by rweigel** [hapi-server/verifier-nodejs#4]
At present, checks abort at 200 ms.  Another try should be attempted at default timeout for browsers and timing should be reported in output.

**Comment by jbfaden** [comment]
I put a cache on my experimental server (http://jfaden.net/HapiServerDemo/hapi) and things are quicker now.  I'm surprised it's still complaining though because the response seems very quick to me.  Could the test be relaxed to 300ms instead?

**Comment by rweigel** [comment]
c17d32c058c3d88e47cd91bfa5109d6f0818ddd5
