### ISSUE TITLE
is.FileContentSame misreports the all parameter request

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#48]
is.FileContentSame misreports the all parameter request.  It correctly reports the number of records (rows) single parameter request, but for the all parameter request it reports "7" not "0".

~~~~~
  ✕: is.FileContentSame() Expect number of rows from one parameter request to match data from all parameter request.; Got:
 # rows in single parameter request = 27 # in all parameter request = 7
~~~~~

**Comment by jbfaden** [comment]
I'll be fixing the bug I have shortly, but I can mock up a server which does this if needed.

**Comment by rweigel** [comment]
Please do. There is little that can be done with this level of detail. I've seen this error before when there is error text in one response. The verifier counts newlines, so the error may be due to non-numeric data in one case.

**Comment by jbfaden** [comment]
Some time you should show me how you develop the nodejs verifier code.  It's such a useful service, and it would be good for more than one of us to be able to add to it.

**Comment by rweigel** [comment]
Do you have a url for this?
