### ISSUE TITLE
3.1 message against 2.0 server

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#49]
https://hapi-server.org/verify-dev/?url=http://planet.physics.uiowa.edu/das/das2Server/hapi&id=Cassini/RPWS/HiRes_LoFreq_Spectra,Bz_100Hz&parameter=Bz&time.min=2008-08-11T12:00:00Z&time.max=2008-08-11T16:00:00Z

The error message is:

✕: [is.HAPITime()](https://github.com/hapi-server/verifier-nodejs/blob/master/is.js#L1199) Expect time column to contain valid [HAPI 3.1 HAPITime strings](https://github.com/hapi-server/verifier-nodejs/tree/master/schemas/HAPI-data-access-schema-3.1.json); Got:
'2008-08-11T12:00:29.383' is not a valid HAPI Time string. (Missing trailing Z.) (First character is not [0-9].)

**Comment by rweigel** [comment]
Closed by https://github.com/hapi-server/verifier-nodejs/commit/2fd109e521efe189e053af1e891a2e56c327f5bf
