### ISSUE TITLE
issue using README.md to set up my own verifier instance

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#5]
I followed the instructions at https://github.com/hapi-server/verifier-nodejs/blob/master/README.md (on Linux Mint 17.3), and everything seems to work except for the section "Command-Line Usage":

~/tmp/verifier-nodejs
spot5> node test.js --url http://jfaden.net/HapiServerDemo/hapi/
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/jbf/tmp/verifier-nodejs/test.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

This was after:
cd ~/tmp/
curl https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install 4
git clone https://github.com/hapi-server/verifier-nodejs.git
cd verifier-nodejs; npm install

**Comment by rweigel** [comment]
0d3e271a6e409bc892e681c28d6f3862c595b848

**Comment by jbfaden** [comment]
Thanks, works for me now.
