### ISSUE TITLE
is.FileContentSame(): Expect number of rows from one parameter request to match data from all parameter request.

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#56]
The warning "✗ is.FileContentSame(): Expect number of rows from one parameter request to match data from all parameter request." should check for an error with the two responses.  The single-parameter read works, but when reading all parameters an error occurs so no rows are sent.  The message says that 8 rows are sent in the all parameter request, and I suspect that this is because of the runtime error message (500) sent.

**Comment by rweigel** [comment]
It counts newlines for that test, so it is parsing the error message. It
stops further "same" tests if the # of rows doesn't match.

If the server sent an HTTP 500, it should have stopped processing. I
suppose one could add a test to see if the response does not start with
digits and if not, conclude an error string was probably sent.

**Comment by rweigel** [comment]
Based on this,
https://github.com/hapi-server/verifier-nodejs/blob/master/tests.js#L840
I think your server sent HTTP 200.
