### ISSUE TITLE
Check that /hapi/ redirects to /hapi; warn if not

### ISSUE THREAD

**Issue by rweigel** [hapi-server/verifier-nodejs#62]

**Comment by berniegsfc** [comment]
I wouldn't require that an HTTP redirect (status code 30x and Location header) is used to ensure that clients obtain the "hapi landing page" with and without a trailing slash.  Jeremy's recent change to the cdaweb server was not implemented with a redirect.

**Comment by rweigel** [comment]
I was thinking that it should warn, because this is the expected behavior in the sense that technically `hapi/` is not correct but it is clearly an error. I suppose for performance reasons one may want to serve the same content without a redirect, but I think this is misleading and people may expect all servers to allow a trailing slash. Thoughts?

**Comment by berniegsfc** [comment]
Technically, `hapi/` is correct and `hapi` can be redirected to `hapi/`.

**Comment by rweigel** [comment]
The [documentation](https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#32-hapi) says the reverse. Are you saying the spec is wrong?

**Comment by berniegsfc** [comment]
Maybe.  I was referring to more general URLs.  `dir/hapi` is a file named `hapi` in the `dir` directory.  `dir/hapi/` is a directory named `hapi` which will return either forbidden, a list of files, or a file name `index.html`.  Nand's hapi server is returning index.html. But if the landing page isn't considered static content, I guess the hapi spec. can define the resource/URL however it wants.
cdaweb.gsfc.nasa.gov/pub
responses with a 301 redirect to 
cdaweb.gsfc.nasa.gov/pub/
which then returns a file listing (index.html if one existed).
