### ISSUE TITLE
verifier generates "allowed.includes is not a function" when run at my site

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#9]
The verifier produces the message "allowed.includes is not a function" when I run it at my site.   I get:

~/tmp/verifier-nodejs
spot5> node verify.js
Listening on port 9999. See http://localhost:9999/
2018-01-22T13:33:55.626Z Request from ::ffff:127.0.0.1: /
2018-01-22T13:34:32.829Z Request from ::1: /
2018-01-22T13:34:53.462Z Request from ::1:
/?url=http://secure-web.cisco.com/19dj6laIuUDkjtb-12eu8oZ3gKqyqFxbQ0RfDK9YeGXjpxRzkWSqDEPIcjlahdHZsg2FccF2MZWfxQvAvdm4DmI4G-66ohSSU_KSEf55pAbIFrQwUaEahWaEDAQt-M7oAA_VpWd792VgRugEc2E03H-XyJnNpGgwgvQ25rrVd5mhSczmYsmfVThoEwDXDmFGjrRlVkUX-eMn3yJZA_z2uH6Tg40hGVt6-4HJYDyO4TF6T4ofYkNmU7ylYuvNwriUcnUjC70F0zvBGEfbzyWPz9Ug4vZxuruX2r9lmCPVyIVKv8vLDc0pFzpDNkJo9xchEix3TbN5fjil_lV9v_VCFu--1nFRQVgfkfgbjqhhKZgcNBMh6oVDhIHr3xnbLqypjlBE1iLmM_Zx4TA3SY680wlYVTa0fusriG0KbjuzRs5gUT0uZAptYCqBIxGNLo4OK/http%3A%2F%2F192.168.0.46%3A9000%2Fhapi
TypeError: allowed.includes is not a function
     at /home/jbf/tmp/verifier-nodejs/verify.js:45:17
     at Layer.handle [as handle_request]

I can expose my server and the one hosted by Bob is good for testing.

**Comment by rweigel** [comment]
Fixed by requiring Node >= 6 1d2d395b23eff183c7e275de75f6a4a143d4a494
